version: "3.0"
services:
  webapp:
    build: .
    tty: true
    image: imgwptest:1.2
    container_name: cntr_wp
    ports:
      - 8080:80
    volumes:
      - vol_wpapp:/var/www/web-apps/
      - vol_nginx_conf:/etc/nginx/conf.d/
    depends_on:
      - mysqldb
  mysqldb: 
    image: mysql:latest
    container_name: cnt_mysqldb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp_devops
      MYSQL_USER: wp_devops
      MYSQL_PASSWORD: devops_123
    volumes:
      - vol_mysqldata:/var/lib/mysql
volumes:
  vol_wpapp:
  vol_mysqldata:
  vol_nginx_conf:
  



    
